-- MySQL Script generated by MySQL Workbench
-- Sat Sep 11 16:57:03 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema delilah
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema delilah
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `delilah` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `delilah` ;

-- -----------------------------------------------------
-- Table `delilah`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delilah`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(60) NOT NULL,
  `nombreCompleto` VARCHAR(60) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `telefono` BIGINT NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `isadmin` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `delilah`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delilah`.`pedidos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `precio_total` FLOAT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `forma_pago` VARCHAR(45) NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_pedidos_users_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `delilah`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `delilah`.`platos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delilah`.`platos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  `precio` INT NOT NULL,
  `url` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `delilah`.`pedidos_has_platos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delilah`.`pedidos_has_platos` (
  `pedidos_id` INT NOT NULL,
  `platos_id` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  PRIMARY KEY (`pedidos_id`, `platos_id`),
  INDEX `fk_pedidos_has_platos_platos1_idx` (`platos_id` ASC) VISIBLE,
  INDEX `fk_pedidos_has_platos_pedidos1_idx` (`pedidos_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_has_platos_pedidos1`
    FOREIGN KEY (`pedidos_id`)
    REFERENCES `delilah`.`pedidos` (`id`),
  CONSTRAINT `fk_pedidos_has_platos_platos1`
    FOREIGN KEY (`platos_id`)
    REFERENCES `delilah`.`platos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
